# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20210411020013) do

  create_table "household_account_books", force: :cascade do |t|
    t.date "worked_on"
    t.string "note"
    t.integer "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "fixed_cost"
    t.string "fixed_cost_1"
    t.string "fixed_cost_2"
    t.string "fixed_cost_3"
    t.string "fixed_cost_4"
    t.string "fixed_cost_5"
    t.string "fixed_cost_6"
    t.string "fixed_cost_7"
    t.string "fixed_cost_8"
    t.string "fixed_cost_9"
    t.string "fixed_cost_10"
    t.string "fixed_cost_11"
    t.string "fixed_cost_12"
    t.string "fixed_cost_13"
    t.string "fixed_cost_14"
    t.string "fixed_cost_15"
    t.string "fixed_cost_16"
    t.string "fixed_cost_17"
    t.string "fixed_cost_18"
    t.string "fixed_cost_19"
    t.string "fixed_cost_20"
    t.integer "fixed_n"
    t.integer "fixed_n_1"
    t.integer "fixed_n_2"
    t.integer "fixed_n_3"
    t.integer "fixed_n_4"
    t.integer "fixed_n_5"
    t.integer "fixed_n_6"
    t.integer "fixed_n_7"
    t.integer "fixed_n_8"
    t.integer "fixed_n_9"
    t.integer "fixed_n_10"
    t.integer "fixed_n_11"
    t.integer "fixed_n_12"
    t.integer "fixed_n_13"
    t.integer "fixed_n_14"
    t.integer "fixed_n_15"
    t.integer "fixed_n_16"
    t.integer "fixed_n_17"
    t.integer "fixed_n_18"
    t.integer "fixed_n_19"
    t.integer "fixed_n_20"
    t.string "variable_cost"
    t.string "variable_cost_1"
    t.string "variable_cost_2"
    t.string "variable_cost_3"
    t.string "variable_cost_4"
    t.string "variable_cost_5"
    t.string "variable_cost_6"
    t.string "variable_cost_7"
    t.string "variable_cost_8"
    t.string "variable_cost_9"
    t.string "variable_cost_10"
    t.string "variable_cost_11"
    t.string "variable_cost_12"
    t.string "variable_cost_13"
    t.string "variable_cost_14"
    t.string "variable_cost_15"
    t.string "variable_cost_16"
    t.string "variable_cost_17"
    t.string "variable_cost_18"
    t.string "variable_cost_19"
    t.string "variable_cost_20"
    t.integer "variable_n"
    t.integer "variable_n_1"
    t.integer "variable_n_2"
    t.integer "variable_n_3"
    t.integer "variable_n_4"
    t.integer "variable_n_5"
    t.integer "variable_n_6"
    t.integer "variable_n_7"
    t.integer "variable_n_8"
    t.integer "variable_n_9"
    t.integer "variable_n_10"
    t.integer "variable_n_11"
    t.integer "variable_n_12"
    t.integer "variable_n_13"
    t.integer "variable_n_14"
    t.integer "variable_n_15"
    t.integer "variable_n_16"
    t.integer "variable_n_17"
    t.integer "variable_n_18"
    t.integer "variable_n_19"
    t.integer "variable_n_20"
    t.string "variable_note"
    t.string "income"
    t.string "income_1"
    t.string "income_2"
    t.string "income_3"
    t.string "income_4"
    t.string "income_5"
    t.string "income_6"
    t.string "income_7"
    t.string "income_8"
    t.string "income_9"
    t.string "income_10"
    t.integer "income_n"
    t.integer "income_n_1"
    t.integer "income_n_2"
    t.integer "income_n_3"
    t.integer "income_n_4"
    t.integer "income_n_5"
    t.integer "income_n_6"
    t.integer "income_n_7"
    t.integer "income_n_8"
    t.integer "income_n_9"
    t.integer "income_n_10"
    t.string "income_note"
    t.index ["user_id"], name: "index_household_account_books_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "email"
    t.string "phone_number"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "password_digest"
    t.string "remember_digest"
    t.boolean "admin", default: false
    t.string "department"
    t.string "reset_digest"
    t.index ["email"], name: "index_users_on_email", unique: true
  end

end
